# All available configuration can be found here:
# https://www.algolia.com/doc/api-client/symfony/configuration/
algolia_search:
    prefix: '%env(APP_ENV)%_'
    indices:
    - name: annonces
      class: App\Entity\Annonce
      enable_serializer_groups: true